### ISSUE TITLE
URL in About Section is "coed" instead of "code"!

### ISSUE THREAD

**Issue by ellsworthjc** [alishahnovin/codecollision#1]
Hello @alishahnovin ! I'm looking forward to jumping into Code Collision! Great work on this project so far. I just wanted to give you a heads up that the URL in the About Section says "_coed_collision.dev" instead of "_code_collision.dev". Unless you're planning on creating a NEW type of collision game, I figured I'd throw it out there!

Thanks again and looking forward to jumping in!

-Connor

**Comment by alishahnovin** [comment]
#hero
